### ISSUE TITLE
Wunschliste (ist klein)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/xoutputfilter#1]
hallo andi,

danke, dass du hier anfängst :-)

alle dinge die die 4er version schon konnte muss ich jetzt hier nicht auflisten. hätte ich gerne alles wieder :-)

die dinge die ich im out5 addon habe könnte ich ja dann fast alle machen.

lg
oliver

**Comment by staabm** [comment]
was ist der vorteil wenn sie hier implementiert sind anstatt in out5?

**Comment by olien** [comment]
Kennst Du den XOutPutfilter für Redaxo4? Damit ist wirklich viel machbar...
Im out5 habe ich einzelne Plugins für die Ersetzungen. Nicht wirklich schön!

**Comment by skerbis** [comment]
Man kann sehr individuelle Filter für Front- und Backend nach Lust und Laune definieren. Was ich mir noch wünsche ist eine Import / Export - Funktion😏

**Comment by olien** [comment]
Die gab es ja in der 4er Version...

**Comment by skerbis** [comment]
Ups! 

Von meinem iPhone gesendet
