### ISSUE TITLE
Front- und Backend-Ersetzungen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/xoutputfilter#18]
Was ist, wenn ich einen Platzhalter sowohl im backend (bspw. strucutre), als auch im frontend ersetzt sehen will? Muss ich diesen dann doppelt anlegen?

**Comment by aeberhard** [comment]
Klasse Alex dass Du dir den outputfilter mal zur Brust nimmst:)
Ja, Backend und Frontend sind zwei unterschiedliche Bereiche. 
Aber ich mach mal ein Issue "kopieren" auf.

**Comment by alexplusde** [comment]
Wäre es nicht besser, man hätte einen Reiter "Ersetzungen" und kann nach "Frontend"/"Backend" filtern?

**Comment by aeberhard** [comment]
Das sind zwei unterschiedliche Plugins, und meiner Meinung nach macht es keinen Sinn da im 
Backend ganz andere Anforderungen da sind als im Frontend ...

**Comment by alexplusde** [comment]
Im Backend in der Artikelansicht habe ich dann halt nen Platzhalter, darum ging es mir. 
![image](https://cloud.githubusercontent.com/assets/3855487/20130284/1a3c3c1a-a656-11e6-9395-499fb066b3e2.png)

**Comment by aeberhard** [comment]
Die Platzhalter hast Du aber auch beim sprog im Backend ...
Und m.M. nach sollte hier auch der Platzhalter zu sehen sein!

**Comment by alexplusde** [comment]
Finde ich schade. In der Block-Vorschau sollte in meinen Augen der echte Content ausgegeben werden, in der Editieransicht natürlich nicht.
