### ISSUE TITLE
Key-Abgleich mit Sprog

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/xoutputfilter#20]
Keys, die in XOutputFilter angelegt werden, sollten nicht in der Liste der nicht ersetzten Platzhalter von Sprog auftauchen und vice versa.
@tbaddade

**Comment by aeberhard** [comment]
Denke nicht dass hier ein Abgleich stattfinden muss. Entweder verwendet man sprog für Sprachersetzungen oder den outputfilter.

**Comment by alexplusde** [comment]
Ich hatte mal gehört, dass du Sprachersetzungen rausnimmst, weil es ja Sprog gibt...

**Comment by alexplusde** [comment]
Und: Habe jetzt entdeckt, dass Frontend-Ersetzungen bei dir ja ohne Präfix/Suffix eingegeben werden. D.h., das Problem mit Keys, die nicht in Sprog auftauchen sollen, kann man umgehen, indem man ein 2. Ersetzungsschema definiert und nicht bspw. so:

###sprogkey###
###xoutputfilterkey###

Aber: Sprog macht halt auch ein bisschen mehr als nur Sprachersetzungen, weshalb es schon wahrscheinlich ist, dass beides parallel verwendet wird.

**Comment by aeberhard** [comment]
Ich werde die default-Einstellungen für Präfix/Suffix ändern und einen conflicts zum sprog im
language-Plugin einbauen.
Die Platzhalter hast Du aber auch beim sprog im Backend ...
