### ISSUE TITLE
Mit englischem Backend geht speichern nicht mehr

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/xoutputfilter#24]
Wenn man als Backendsprache "Englisch" auswählt, kann man weder neue Einträge hinzufügen, noch bestehende bearbeiten.

Der Benutzer hat die Rechte, bekommt die Bearbeiten-Seite gezeigt, aber nach dem "Speichern" bleibt er auf der Seite und die Änderungen werden ignoriert.

Redaxo: 4.7
xoutputfilter: 2.0

**Comment by aeberhard** [comment]
Issue gehört hier hin https://github.com/aeberhard/xoutputfilter
