### ISSUE TITLE
Viele Notice Meldungen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/xoutputfilter#25]
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 141
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 146
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 150
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 152
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 157
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 159
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 167
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 176
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 184
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 187
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 189
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 194
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 196
Notice: Only variables should be assigned by reference in /Applications/MAMP/htdocs/rex5basic5/redaxo/src/addons/xoutputfilter/plugins/backend/pages/index.php on line 201

**Comment by aeberhard** [comment]
Hey Oliver, hast Du da evtl. eine alte Version ?

**Comment by alexplusde** [comment]
Kann ich nicht bestätigen. ich mach's zu - andernfalls wieder aufmachen,
