### ISSUE TITLE
Prio-Feld

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/xoutputfilter#28]
Ich würde mir wünschen, dass man die Reihenfolge der Bearbeitung nicht über den key festlegen muss, sondern ein Prio-Feld hat und die Abarbeitung sich danach richtet.

**Comment by aeberhard** [comment]
Ich sehe da jetzt zwar nicht unbedingt einen Sinn darin :) ist ja noch ein zusätzliches Feld das man evtl. auch anpassen muss. Ich nehm das prio-Feld aber mal schon in die Tabelle auf ... wenn mal Zeit ist ...

**Comment by alexplusde** [comment]
Szenario: Ich hatte in R4 öfters den Fall, dass der key die Funktion beschreibt, aber die Reihenfolge der Abarbeitung wichtig war und dadurch immer einen präfix verwenden musste.
