### ISSUE TITLE
Fehler beim Übernehmen: Angeblich kein key

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/xoutputfilter#29]
Gerade hatte ich das Problem, dass ich eine Ersetzung im Bearbeitungsmodus von aktiv auf inaktiv schalten wollte und diese Änderung nicht übernommen werden konnte, da angeblich kein key vergeben worden sei. Ein key war jedoch eingetragen.

Reproduzieren kann ich den Fehler allerdings nicht.

**Comment by aeberhard** [comment]
War das eine nicht abgefangene Fehlermeldung oder eine Redaxo-Formatierte Meldung?

**Comment by alexplusde** [comment]
Redaxo-formatiert.

**Comment by alexplusde** [comment]
Mir ist das gerade nochmal passiert und habe versehentlich wohl tatsächlich keinen Key vergeben, sondern nur den Namen (als key).
