### ISSUE TITLE
Addon-Name

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/xoutputfilter#3]
Gab's dazu schon eine Diskussion in Slack? Bleibt es bei XOutputFilter? Wollte man sich nicht von rex_ und x-Präfixen trennen?

**Comment by aeberhard** [comment]
Nein ich glaube es gab speziell hierzu noch keine Diskussion.
Wäre aber auch kein Problem mit **outputfilter**

**Comment by schuer** [comment]
+1 für `outputfilter` oder `output_filter`

**Comment by tbaddade** [comment]
Dazu müsste man sich das Addon einmal ansehen können. Outputfilter finde ich nicht so sinnvoll, da es schon einen gleichnamigen EP gibt und ich vermute, dass das Addon sich nicht nur diesen einen EP bedient?

**Comment by aeberhard** [comment]
Das Addon bedient im Frontend und Backend den EP OUTPUT_FILTER

**Comment by skerbis** [comment]
Dann ist es eine OutputfilterGUI

**Comment by alexplusde** [comment]
+1 für den Vorschlag @schuer - dass ein Addon, das einen Menüpunkt erzeugt, in der Regel eine GUI mitliefert, macht das UI redundant.

**Comment by alexplusde** [comment]
Dynamic Filter
Dynamic Replace
war mir noch als Idee eingefallen, weil das mehr die Aufgabe beschreibt als die Funktion dahinter.

**Comment by schuer** [comment]
Oder

Content Filter
Instant Filter
Global Filter / Global Replacer

**Comment by alexplusde** [comment]
Ich zieh meinen Wunsch nach Änderung des Namens zurück, wenn es die Veröffentlichung beschleunigt.

**Comment by schuer** [comment]
+1

**Comment by olien** [comment]
+1

**Comment by schuer** [comment]
Okay, @alexplusde war ja nun Initiator des Threads und hat ihn am Ende wieder zurückgezogen. Und weil der @aeberhard keine besondere Präferenz zu haben schien und wir anderen auch eher ratlos waren, können wir den Namen vermutlich nun einfach bei `xoutputfilter` belassen und das von vielen gewünschte erste Beta-Release veröffentlichen, was?

Falls noch jemand dagegen sein sollte, einfach hier bescheid geben :)
