### ISSUE TITLE
Wunsch: Beta in den Installer

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/xoutputfilter#31]
Beim Redaxo-Tag waren wieder ein paar dabei, die nicht wussten, dass es das Addon schon portiert für R5 gibt. Ich finde, die Beta sollte deshalb auch im Installer zu finden sein.

Ich möchte da keinen Druck ausüben, aber in meinen Augen kann man die Version jetzt schon produktiv einsetzen - wenn das Addon den Beta-Status verlässt, wird sich ja grundsätzlich nicht viel ändern.

@aeberhard du bist Lead des FOR-Addons, wärst du damit einverstanden? Was meinen die anderen? @tbaddade du hast es ebenfalls in Verwendung.

**Comment by schuer** [comment]
Ich würde auch empfehlen, eine Beta in den Installer zu stecken. Das ist die zentrale Stelle, an der Nutzer:innen Addons bemerken, und wenn ein Addon nicht im Installer ist, bekommt es kaum Aufmerksamkeit.

Allerdings müsste vorher der Name geklärt werden, um den richtigen Addon-Key zu sichern: #3

**Comment by schuer** [comment]
Nach einiger Slack-Abstimmung zu dem Thema, ist die Beta nun in den Installer gegangen. @aeberhard, ich hoffe, das ist in deinem Sinne. Bei der final 3.0.0 halten wir uns natürlich raus :)

**Comment by tbaddade** [comment]
> @tbaddade du hast es ebenfalls in Verwendung.

@alexplusde wie meinst du das?

**Comment by aeberhard** [comment]
@schuer @alexplusde ist vollkommen in Ordnung, dafür ist doch FOR da :)
Sorry aber ich hoffe ab dieser Woche hab ich wieder Zeit für den xoutputfilter, und ich war ja nie gegen den Namen ...
