### ISSUE TITLE
Frontend vs. Sprache

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/xoutputfilter#41]
Mir ist nicht ganz klar, warum bei "Frontend" überhaupt mehrere Sprachen angezeigt werden: 
![image](https://user-images.githubusercontent.com/688274/31883652-dc3f8df2-b7ea-11e7-89d6-ba8e6af02394.png)
Wenn ich eine änderung in einer Sprache mache oder sie aktivere/deaktiviere, ist das auch in der anderen Sprache so. Dann kann man das doch auch komplett abschalten, oder?

**Comment by cukabeka** [comment]
ah, ich glaube, ich habe es verstanden: aktiv/inaktiv ist in sync, aber der content ist bei den sprachen unterschiedlich. evtl kann man das noch in die erklärungstexte setzen?

**Comment by IngoWinter** [comment]
> evtl kann man das noch in die erklärungstexte setzen?
Du bist doch grad im Thema - mach doch nen PR dazu...
