### ISSUE TITLE
Fehler: Filter auf Artikel welche im Root der Struktur sind. Fix vorhanden

### ISSUE THREAD

**Issue by rkemmere** [FriendsOfREDAXO/xoutputfilter#43]
Wenn Artikel im Root der Struktur sind, wird der Xoutputfilter dort nicht ausgeführt.
Ursache ist das Initiale setzen der CategoryID auf 0. Diese sollte -1!

` public static function frontendReplace(rex_extension_point $ep)
        $categoryid = -1;`

Viele Grüße
Ronny

**Comment by aeberhard** [comment]
Danke Dir Ronny!
