### ISSUE TITLE
Links nach der Form redaxo://articleID werden nicht ersetzt

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/xoutputfilter#44]
Wenn ich in einer Sprachersetzung einen "Redaxo Link" benutze, dann wird dieser im Frontend nicht aufgelöst.

` Lorem <a href="redaxo://12">Ipsum</a> quid`

Sollte im Frontend zu 

` Lorem <a href="/impressum.html">Ipsum</a> quid`

werden, das passiert aber nicht.

**Comment by alexplusde** [comment]
Ich würde es anders lösen mit einer PHP-Ersetzung und dann `rex_getUrl(12)`.
