### ISSUE TITLE
Parameter mit übergeben / Shortcodes

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/xoutputfilter#46]
Toll wäre, wenn es möglich wäre, einfache Parameter mit zu übergeben, dann ließen sich Ersetzungen als mini-Templates verwenden.

z.B.

`Wir empfehlen [[WICHTIGER-LINK[bla]]] und [[WICHTIGER-LINK[blub]]]`

könnte via PHP Ersetzung zu so etwas werden:

Wir empfehlen `<a href="/artikel?param=bla">bla</a>` und `<a href="/artikel?param=blub>bulb</a>`

**Comment by stefan-beyer** [comment]
#2

**Comment by stefan-beyer** [comment]
@cukabeka 
Wie stellst du dir denn die Konfiguration/Arbeitsweise für die gewünschte Funktionalität vor?

 - Möglichkeit 1: Man schreibt einen Regulären Ausdruck dafür ... das scheint (nach Sichtung des Codes) von xoutputfilter vorgesehen zu sein.
 - Möglichkeit 2: die Parameter werden direkt, z.B. per Platzhalter, in die Ersetzung eingefügt. Die Ersetzung ist dann sozusagen ein kleines Template mit Platzhaltern...
Beispiel: Marker: `[[Marker param="wert"]]` und Ersetzung `"link zu {param}"` wird zu `"link zu wert"`
Nachteil: wenn es nicht gleich durch eine ganze Templateing-Engine gestützt wird, könnte es sehr einschränkend sein.
- Möglichkeit 3: Eine Callback-Funktion wird aufgerufen (wie das bei WP der Fall ist), die dann die Ersatzzeichenkette zurückgibt:
Beispiel: Marker: `[[Marker param="wert"]]`
```
funktion marker_callback($params) {
  return "link zu ".$params['param'];
}
```

Die Funktion nach Möglichkeit 2 oder 3 lässt sich allerdings nicht einfach als xoutputfilter plugin formulieren, denn die Verarbeitung der vorgesehen Filter-Typen sind im Kern von xoutputfilter implementiert - wenn ich das richtig gesehen habe.

**Comment by staabm** [comment]
Ohne jemand ärgern zu wollen, würde ich diesen vorgang wg duplicate zu https://github.com/FriendsOfREDAXO/xoutputfilter/issues/2 schließen wollen.

Evtl. Hab ich in einer ruhigen minute mal zeit einen rex-var ansatz beizusteuern
