### ISSUE TITLE
Frontendersetzung innerhalb von Frontendersetzungen

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/xoutputfilter#61]
Hey,

kurze Frage zu den Frontendersetzungen. Ich ersetze aktuell einen Platzhalter mit einem Formular. Darin sind einige Sprachersetzungen, die problemlos ersetzt werden. Allerdings ist ein Platzhalter dabei, den ich gerne mit einer weiteren Frontendersetzung austauschen möchte, weil ich an dieser Stelle einen Link brauche, der aus Redaxo kommt. In der Version aus dem Installer wird dieser Platzhalter allerdings nicht ersetzt. Habe ich das unter Umständen einfach nur falsch konfiguriert oder ist das so aktuell (noch) nicht vorgesehen?

**Comment by aeberhard** [comment]
Hallo Pascal,
das ist so nicht vorgesehen. Weiss jetzt gerade nicht die genaue Reihenfolge aber die Sprachersetzungen werden als letztes ausgeführt. Frontend vorher und nur einmal.

**Comment by pschuchmann** [comment]
Hab jetzt kürzlich raus gefunden, was es war und es war einfach nur ein Fehler meinerseits. Die Ersetzung sollte in einer PHP Definition eines YForm Choice Feldes kommen und die war schlichtweg nicht korrekt 😊
