### ISSUE TITLE
Frontendersetzungen funktionieren nicht im Root (Installer-Version)

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/xoutputfilter#62]
Verschiebe ich den Artikel in eine Kategorie klappt es. Liegt der Artikel im Root, nicht.

**Comment by skerbis** [comment]
Sehe gerade in der GitHub-Version ist's gefixt. Wäre Zeit für ein Release oder?

**Comment by skerbis** [comment]
ping @aeberhard

**Comment by aeberhard** [comment]
Ich bin da noch an einigen anderen Dingen dran. Aber es wird demnächst dann ein Release geben!

**Comment by alexplusde** [comment]
Kann das Problem bestätigen! Gibt es da die Möglichkeit, vorab zu fixen, weil die Website online gehen soll...

**Comment by skerbis** [comment]
@alexplusde @aeberhard  die aktuelle Github Version behebt das Problem
